spring:
  datasource:
    url: jdbc:mysql:///jpa?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    data-username: root
    data-password: root
    schema-username: root
    schema-password: root
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    #initialization-mode: always
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
    #控制台显示SQL
    show-sql: true